variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ANDROID_HOME:           $PWD/android-sdk

before_script:
  - apt-get update
  - apt-get -y install ca-certificates podman buildah
  # Switch to iptables legacy, as GitLab CI doesn't support nftables.
  - apt-get -y install --no-install-recommends iptables
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - buildah info

after_script:
  - sha256sum build/*

bullseye-jdk11:
  image: debian:bullseye-slim
  script:
    - podman build --cap-add=sys_admin --device /dev/fuse --file build.Containerfile .
    - export CID=`podman create de.schildbach.oeffi nop`
    - mkdir -p build/
    - podman cp $CID:/ build/
    - podman rm -i $CID
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk

bookworm:
  image: debian:bookworm-slim
  script:
    - buildah build --cap-add=sys_admin --device /dev/fuse --file build.Containerfile --output build .
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk
