variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ANDROID_HOME:           $PWD/android-sdk

before_script:
  - apt-get update
  - apt-get -y install ca-certificates podman

after_script:
  - sha256sum build/*

bullseye-jdk11:
  image: debian:bullseye-slim
  script:
    - podman build --file build.Containerfile .
    - export CID=`podman create de.schildbach.oeffi nop`
    - mkdir -p build/
    - podman cp $CID:/ build/
    - podman rm -i $CID
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk

bookworm-jdk17:
  image: debian:bookworm-slim
  script:
    - podman build --events-backend none --file build.Containerfile --output build .
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk

jammy-jdk11:
  image: ubuntu:jammy
  script:
    - podman build --file build.Containerfile .
    - export CID=`podman create de.schildbach.oeffi nop`
    - mkdir -p build/
    - podman cp $CID:/ build/
    - podman rm -i $CID
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk

lunar-jdk17:
  image: ubuntu:lunar
  script:
    - podman build --events-backend none --file build.Containerfile --output build .
  artifacts:
    name: oeffi-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/*.apk
